---
# jenkins는 클러스터 밖에 설치를 시작함
# 설치 자체는 https://velog.io/@thdrldud369/Jenkins-%EC%84%A4%EC%B9%98 를 참고함

# jenkins 구동을 위하여 jdk가 필요
- name: "jenkins installation at host vm : install jdk"
  shell: | 
    sudo apt install openjdk-17-jdk -y
  tags:
    - jenkins
    - openjdk
    - demo-ex
    - demo-ex-jenkins

# 재실행시에도 돌도록 wget -l, gpg --batch --yes 로 덮어쓰기
- name: "jenkins installation at host vm : get pgp key"
  shell: |    
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  tags:
    - jenkins
    - demo-ex
    - demo-ex-jenkins

- name: "jenkins installation at host vm : install jenkins"
  shell: | 
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    sudo apt update
    sudo apt install jenkins -y
  register: output
  tags:
    - jenkins
    - demo-ex
    - demo-ex-jenkins
  
- debug:
    var: output
  tags: 
    - jenkins
    - demo-ex
    - demo-ex-jenkins
