---
# jenkins는 클러스터 밖에 설치를 시작함
- name: "jenkins installation at host vm : get pgp key"
  shell: | 
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key |sudo gpg --dearmor -o /usr/share/keyrings/jenkins.gpg
  tags:
    - jenkins
    - demo-ex
    - demo-ex-jenkins

- name: "jenkins installation at host vm : install jenkins"
  shell: | 
    sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt update
    sudo apt install jenkins -y
  tags:
    - jenkins
    - demo-ex
    - demo-ex-jenkins


# 향후 아래와 같은 부분의 코드화가 필요
# 위 방법으로 jenkins 설치 후 
# jenkins계정에 docker 실행권한 부여 
# docker-pipeline, git parameter, workspace cleanup 플러그인 설치
# git-credential, imageRegistry-credential 생성
